### ISSUE TITLE
Possible to create cheatsheets in other software/language?

### ISSUE THREAD

**Issue by wbuchanan** [GeoCenter/StataTraining#10]
I have 0 access to Adobe products (other than the PDF reader) and was wondering if it would be possible to create versions of the cheat sheets that use LaTeX, markdown, or something similar.  Aside from making it easier for others to help contribute, I think it would be fairly useful since it could make sections of the cheat sheets modular (e.g., have a module for a mergeing/appending tile that can be updated independently of the rest of the cheat sheet overall).

**Comment by tessam30** [comment]
We got our inspiration for the cheat sheets from the [R-Studio folks](https://www.rstudio.com/resources/cheatsheets/how-to-contribute-a-cheatsheet/). They have created a template to use their formatting and color scheme if that is useful for you. We chose to make ours in Illustrator for greater flexibility and functionality. If you know of an efficient way of doing this in markdown, we are happy to contribute. Otherwise, we will probably keep this in Adobe format for the foreseeable future. 

Also, we are working on a programming cheat sheet to cover the basics of r-class e-class, scalars, matrices, macros, functions and loops, etc. Once we get a draft done we'd love any feedback you have if that's of interest to you.

**Comment by wbuchanan** [comment]
@tessam30 I recognized the format/layout, but never looked into how they were doing things.  I'm not sure if Markdown has the grammar available for those types of things.  There are probably other web frameworks (there are definitely some Jekyll templates that achieve something analogous), but it definitely wouldn't look as polished.  I'm more than happy to provide feedback on anything.

**Comment by tessam30** [comment]
@wbuchanan - we finished a draft of the final intro to [programming cheat sheet](https://github.com/GeoCenter/StataTraining/raw/gh-pages/pdf/StataCheatSheet_programming_2016_June.pdf). It's obviously limited in what it can cover, but thought it would be a gentle introduction to programming that would round out the rest of the cheat sheets. If you have any feedback, let us know.
